# Generated by Django 5.2 on 2025-04-26 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801XXXXXXXXX'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=10, verbose_name='Address Type')),
                ('division', models.CharField(max_length=50, verbose_name='Division')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('upazila', models.CharField(max_length=50, verbose_name='Upazila/Thana')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('delivery_area', models.CharField(max_length=100, verbose_name='Delivery Area')),
                ('complete_address', models.TextField(verbose_name='Complete Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Address')),
            ],
            options={
                'verbose_name': 'Delivery Address',
                'verbose_name_plural': 'Delivery Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
