# Generated by Django 5.2 on 2025-04-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='complete_address',
        ),
    ]
