# Generated by Django 5.2 on 2025-04-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('maximum_discount', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('minimum_spend', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
            ],
        ),
    ]
