# Generated by Django 5.2 on 2025-04-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_click_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='apparel_size',
        ),
        migrations.CreateModel(
            name='ApparelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apparel_sizes', to='products.product')),
            ],
        ),
    ]
