# Generated by Django 5.2 on 2025-04-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_apparel_size_apparelsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apparelsize',
            old_name='Product',
            new_name='product',
        ),
    ]
