# Generated by Django 5.2 on 2025-04-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_apparelsize_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparelsize',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
